### PR TITLE
Align with up-client-android-java version 0.1.2

### PR DESCRIPTION
**Pull request by neelam-kushwah**
This PR addresses issue #8.

This project depends on the `up-client-android-java` library, which internally utilizes `up-java` version 0.1.9 and `up-core-api` version 1.5.7.

### CODE REVIEW

**Review by stevenhartley — APPROVED** [review]
LGTM. COVESA/uServices have been updated to 1.5.7 of core-api

**Review by stevenhartley — CHANGES_REQUESTED** [review]
.jar file was included in the commit

**Comment by neelam-kushwah** [comment]
> .jar file was included in the commit

It was there , I deleted it in this PR.

**Comment by stevenhartley** [comment]
> > .jar file was included in the commit
> 
> It was there , I deleted it in this PR.

duh of course, sorry Neelam!

**Review by stevenhartley — APPROVED** [review]

**Pull request merged**
